### ISSUE TITLE
reference error: hub is not defined

### ISSUE THREAD

**Issue by venkateshpotluri** [jw84/messenger-bot-tutorial#10]
I am unable to link the app to the web hook by following this tutorial or even cloning the repository. there are 2 issues:
1. if I add the code to the /webhook url, face book gives me a page not found error while adding the web hook.
2. if I add the code to '/', I get an internal server error. on checking the heroic logs, I get this.
reference error: hub is not defined and it points to the following line in the index.js file.
res.send(hub.query['hub.challenge

'])

**Comment by jellyfangs** [comment]
There's an error in your code. 

```
res.send(hub.query['hub.challenge'])
```

should be

```
res.send(req.query['hub.challenge'])
```

**Comment by venkateshpotluri** [comment]
Ya. Sorry, my mistake. 

Thank you.
Regards,
Venkatesh Potluri
Http://www.venkateshpotluri.me
