### ISSUE TITLE
No matching user found

### ISSUE THREAD

**Issue by Lmendev** [jw84/messenger-bot-tutorial#12]
Hello !

I followed the guide and console shows me the next message:
Error:  { message: '(#100) No matching user found'

bot never response..
any ideas ?
thanks!

**Comment by jellyfangs** [comment]
Can you explain some more? The webhook has been set and verified? You have subscribed to the Facebook Page's messages? The chat bot app is up and running?

**Comment by pacozaa** [comment]
https://developers.facebook.com/bugs/230322797329131/?hc_location=ufi
https://developers.facebook.com/bugs/578746852290927/

@lmendoza92

**Comment by xbklairith** [comment]
possibly ,  a recipient (sender.id)  is invalid

**Comment by Arif1310** [comment]
Hello!
I have the same issue, but my bot answer me and the answers are doubled.

**Comment by ranjith29h** [comment]
@Arif1310 have you solved it ? Same problem here

**Comment by Lmendev** [comment]
never solved,

I had to change my project years ago. This repo seems to be out of maintenance.

I'll close the issue due to inactivity
