### ISSUE TITLE
CURL ERRNO=51

### ISSUE THREAD

**Issue by SIRHAMY** [jw84/messenger-bot-tutorial#13]
Facebook now requires connections over https, which seems to mean you need an SSL certificate involved to use the messenger bot platform. May be out of scope of this tutorial, but worth mentioning. Through your tutorial, here's the error I received from FB:

`The URL couldn't be validated. Callback verification failed with the following errors: curl_errno = 51; curl_error = SSL: no alternative certificate subject name matches target host name 'professordex.heroku.com'; HTTP Status Code = 200; HTTP Message = Connection established`

**Comment by jellyfangs** [comment]
Thanks for the tip! On Heroku they offer a starter SSL for free. Are you running the chat bot on your own server?

**Comment by SIRHAMY** [comment]
Interesting. I was running it on my own server then moved over to Heroku to see if it worked. I'm new to Heroku, so I didn't know that was an option. I'll go try it out.
