### ISSUE TITLE
Call back verification failed on Facebook

### ISSUE THREAD

**Issue by fidjez** [jw84/messenger-bot-tutorial#15]
I follow every step but when I put the callback URL and Verify Token I have an error message : the url couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 503; HTTP Message = Service Unavailable. 

There is a way to fix it? 

Thank you.

**Comment by jellyfangs** [comment]
Is the server available online? Is the callback URL correct?

**Comment by kiranvm** [comment]
Hi Jerry,
I am facing similar issue, Call back verification failed. but message is bad gateway

> The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 502; HTTP Message = Bad Gateway

The heroku deployment URL is accessible. Please share if you have any suggestions.

Thank you.

**Comment by kiranvm** [comment]
Please ignore the previous comment. I named Procfile as procfile

**Comment by sarnshreya** [comment]
I am facing this issue too.It shows 
The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 503; HTTP Message = Service Unavailable
And the heroku link seems to be broken with this message-

An error occurred in the application and your page could not be served. Please try again in a few moments.
If you are the application owner, check your logs for details.

**Comment by sarnshreya** [comment]
The heroku log shows-the app crashed

2016-07-28T11:41:39.150069+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)

2016-07-28T11:41:39.150070+00:00 app[web.1]:     at startup (node.js:148:18)

2016-07-28T11:41:39.225296+00:00 heroku[web.1]: Process exited with status 1

2016-07-28T13:24:05.344533+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/?hub.mode=subscribe&hub.challenge=432092788&hub.verify_token=fb_bot" host=fb-121071064.herokuapp.com request_id=77443caa-168e-4428-9f43-9611d8230b9e fwd="66.220.146.21" dyno= connect= service= status=503 bytes=

2016-07-28T13:36:37.043656+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=fb-121071064.herokuapp.com request_id=03ed313b-0930-4e12-8303-1af63446a429 fwd="103.204.168.142" dyno= connect= service= status=503 bytes=

2016-07-28T13:36:37.942331+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=fb-121071064.herokuapp.com request_id=ca3b7c09-e44c-4fbb-97e1-156393b9d483 fwd="103.204.168.142" dyno= connect= service= status=503 bytes=

2016-07-28T13:40:46.783907+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=fb-121071064.herokuapp.com request_id=928318db-97b2-44c3-ae68-0a5cb20c692f fwd="103.204.168.142" dyno= connect= service= status=503 bytes=

**Comment by ghost** [comment]
Having the same problem. 

It won't validate, and the heroku logs show it crashed!

**Comment by ghost** [comment]
I tried "heroku open" in the terminal, and my app could not be opened in the browser - I received an Application Error. I think the problem lies in that the Webhook endpoint isn't working correctly.

**Comment by hellohuman** [comment]
Had the same problem, even though there was a Procfile it was giving me npm start errors. Adding:

"start": "node index.js"

To the package.json file fixed it for me 😄

**Comment by chipcerio** [comment]
I fixed this by adding the node_modules/ in the .gitignore

**Comment by socioboard** [comment]
getting same error for .net core mvc while adding the cal back url in webhooks
 The URL couldn't be validated. Callback verification failed with the following errors: curl_errno = 56; curl_error = Received HTTP code 502 from proxy after CONNECT; HTTP Status Code = 502; HTTP Message = Private address

**Comment by Avinash1992** [comment]
getting same error for .net core mvc while adding the cal back url in webhooks
The URL couldn't be validated. Callback verification failed with the following errors: curl_errno = 56; curl_error = Received HTTP code 502 from proxy after CONNECT; HTTP Status Code = 502; HTTP Message = Private address

**Comment by JShilpa** [comment]
Facing same issue.

**Comment by JShilpa** [comment]
I solved this issue by setting my Wit Token on the command line.
 heroku config:set WIT_TOKEN='your_token_here'.
You can find your Wit token at Settings > Server Access Token.
Hope this helps.

**Comment by lornatumuhairwe** [comment]
Faced the same issue but I noticed that you should set the VERIFY_TOKEN using **heroku config:add VERIFY_TOKEN=your_verification_token_here** in your terminal before verifying your webhook on the developer facebook page.

**Comment by Chanyadav** [comment]
I am using ngrok to webhook facebook with other application but i am facing this error when i try adding to the URL " The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 502; HTTP Message = Bad Gateway". 

Please help me in fixing this.

**Comment by babutritran** [comment]
My solution is to restart the server or close all wed before paste URL callback

**Comment by 19sriram** [comment]
restarted server but couldn't come up with a solution. Still the app is showing crashed and facebook is showing URL cannot be validated..

**Comment by Chanyadav** [comment]
Hey,
Since I had set up my server on local . I used NGROK to expose my local to
global . Try using this to webhook with FB.

Thank you!

**Comment by kamesh231** [comment]
I was hitting with error 403. The issue was with Config Vars declared in Heroku APP. I had a typo in the name used. The variable name mentioned was 'VERIFICATION_TOKEN' where as in my callback code I was referring it as 'VERIFY_TOKEN'. After fixing this the issue was resolved

**Comment by SammyMwanyasi** [comment]
stll facing the problem? in the VERIFY_TOKEN write a name your choice eg **mytoken** then on heroku go to **settings** then `select reveal config var` add Verify_TOKEN and value **mytoken**

**Comment by ABinfinity** [comment]
i tried heroku open command and my web page opens perfectly, i also add verify_token on heroku but when i setup webhook it shows following error:"The url could not be validated.Callback verification failed with following errors:HTTP status code = 500,HTTP Message= Internal Server error"..please tell me what to do to fix this error.

**Comment by SammyMwanyasi** [comment]
Internal Server Error means `VERIFY_TOKEN` and other User Parameters offered by Facebook are not properly configured

**Comment by manudguru** [comment]
The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 500; HTTP Message = Internal Server Error


I m having this issue 
i have a wordpress website .

Plz help

**Comment by abhijeetdhawas** [comment]
The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 402; HTTP Message = Payment Required


i am having this issue

Please help

**Comment by tu20011022** [comment]
Having same issue T T

Callback verification failed with the following errors: HTTP Status Code = 502; HTTP Message = Bad Gateway

I already set the VERIFY_TOKEN, and it still not work.

Please

**Comment by Hateefa** [comment]
I am having the same issue:

The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 502; HTTP Message = Bad Gateway

Even tried to add /webhook/ at the end but it doesn't work.

**Comment by buidairadio** [comment]
I am having the same issue:
The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 502; HTTP Message = Bad Gateway
:(

**Comment by Beezai** [comment]
> Hi Jerry,
> I am facing similar issue, Call back verification failed. but message is bad gateway
> 
> > The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 502; HTTP Message = Bad Gateway
> 
> The heroku deployment URL is accessible. Please share if you have any suggestions.
> 
> I am having this problem, can anyone help me'

**Comment by Israr-Mughal** [comment]
The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 502; HTTP Message = Bad Gateway

Even tried to add /webhook/ at the end but it doesn't work.

Any suggestion to solve this error.

**Comment by Beezai** [comment]
If you have all token set up in heroku and verify token in fb messanger app and again facing same issue then do this.

From requirement.txt file 
Delete the line : setuptool and update the file. 
Your problem should be solved.

**Comment by ysernah** [comment]
Tuve el mismo problema era porque no instale las dependecias comando npm i

**Comment by AnjanaDhakal** [comment]
The URL couldn't be validated. Callback verification failed with the following errors: curl_errno = 28; curl_error = Operation timed out after 6000 milliseconds with 0 bytes received; HTTP Status Code = 200; HTTP Message = Connection established

work fine in glitch
Any suggestion to solve this error.
Thank you in advance
