### ISSUE TITLE
Message should be in Double Quotes and not Single?

### ISSUE THREAD

**Issue by swapnilborkar** [jw84/messenger-bot-tutorial#17]
When committing changes to git, the guide mentions the command: git commit --message 'hello world'
referring to a path. Needs to be replaced with "hello world" instead?

**Comment by jellyfangs** [comment]
I started out in Python and in that world it does not matter: http://stackoverflow.com/questions/143714/is-there-any-difference-between-string-and-string-in-python

So I carry that and the lack of semicolons into the JS world.

In JS there's no preferred method as well: http://stackoverflow.com/questions/242813/when-to-use-double-or-single-quotes-in-javascript
