### ISSUE TITLE
local test

### ISSUE THREAD

**Issue by timothylhuillier** [jw84/messenger-bot-tutorial#2]
Hi,

It's not possible to use localhost url ? Because push for test is very not attractive.
Do you have a solution for that, to use reserve proxy ?

Thanks

**Comment by malditojavi** [comment]
Uh I'd say this is **not** possible because it would require to have a copy of Facebook running in your machine.

**Comment by timothylhuillier** [comment]
Hi @malditojavi normally, it's possible but I don't know, How.
Maybe with local server with Dydns on our box.

**Comment by timothylhuillier** [comment]
@MohamedBassem Give me this perfect tools for this case : https://ngrok.com/

**Comment by jellyfangs** [comment]
Yes, use ngrok to expose the localhost via ngrok url. You can then update the webhook url after to another server.
