### ISSUE TITLE
Loading indicator when opening bot conversation

### ISSUE THREAD

**Issue by alexbartisro** [jw84/messenger-bot-tutorial#21]
Hello,

I followed the tutorial, and got a nice bot working, but I have a question: when someone opens a conversation with the  bot from mobile, a loading indicator is displayed continuously, until the person sends the first message. Is this normal?

And secondly, can I get a request when someone opens the conversation for the first time? So basically, I want the bot to be the one that sends the first message, and not wait for the person to write.

Thanks for the great tutorial!
![img_2899](https://cloud.githubusercontent.com/assets/6096120/16186210/ea6070e0-36d1-11e6-92bd-e262e0197f31.jpg)

**Comment by jellyfangs** [comment]
1. That indicator behavior is not normal.
2. No, your chat bot can not initiate the conversation. The user has to be the first one to message. There after you can set the chat bot to be on a scheduler that then sends out future messages.

**Comment by alexbartisro** [comment]
For the bot to send the first message, you can set a greeting message. See here https://developers.facebook.com/docs/messenger-platform/implementation#welcome_screen

**Comment by stephenhuh** [comment]
@trusk89 this is no longer the case I believe:
Please check out the new "Get Started" Button
https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button

**Comment by alexbartisro** [comment]
@stephenhuh both work. Get Started is in case you want to direct your used to do some action from the beginning.
