### ISSUE TITLE
other people cant chat with my bot

### ISSUE THREAD

**Issue by adriaanbalt** [jw84/messenger-bot-tutorial#23]
Not sure why, everything is setup but other people, not admins, are unable to chat with the bot.  i've made the app public in Facebook developer "App Review" but I havent completed my submission. Do I need to do that first?

**Comment by jellyfangs** [comment]
Until you have been approved by Facebook Messenger team the chat bot is not open to the public.

You have to add users as testers in your Facebook Page settings otherwise the messages don't get relayed. 

Good luck.

**Comment by webtaculars** [comment]
My bot has been approved by facebook. I have used "send to messenger plugin" .  I works fine on my desktop but sometimes the plugin does not show up in my mobile. Is there any bug?

**Comment by tanmayrajani** [comment]
I am required to add a Privacy Policy URL. Can't submit it for review without that. Any idea/workaround for this?

**Comment by tanmayrajani** [comment]
Messenger bot reviewers were actually liberal for the Privacy Policy. I just had one paragraph regarding this unlike what we see in other apps' privacy policy.. but still got approved. Way to go!

**Comment by kunal047** [comment]
@jw84 My bot has been approved but still people other than admin and tester are not able to chat. What's wrong ?

**Comment by tanmayrajani** [comment]
@kunal047 maybe you have not yet made it public? you can do that here: https://developers.facebook.com/apps/APP_ID/review-status/

**Comment by kunal047** [comment]
@tanmayrajani Yes. You were right.  Thank you.
