### ISSUE TITLE
Only working with my id

### ISSUE THREAD

**Issue by touhi99** [jw84/messenger-bot-tutorial#3]
Hello using these steps, getting responds only using from my id, not any other peoples ID , any idea why?

**Comment by jellyfangs** [comment]
Chat bots have to be approved by Facebook before they can engage with the public. I'm writing up a tutorial how to do that next.

For now you can add friends as testers to your Facebook Page to have the chat bot talk to them.

**Comment by touhi99** [comment]
ok thanks , also how about a tutorial to connect an AI brain with messenger app?

**Comment by jellyfangs** [comment]
Yup, also on the way. Prob Monday.

**Comment by touhi99** [comment]
ok sure, can i ask a few things also about chatbot, should i ask here or i will mail you?
