### ISSUE TITLE
NOT A FUCKING TUTORIAL, U PIECE OF SHIT

### ISSUE THREAD

**Issue by ghost** [jw84/messenger-bot-tutorial#39]
I DON'T UNDERSTAND THIS!!!!!!!

You can also skip the whole thing by cloning this git repository here, running npm install, and run a server somewhere. MAKES NO SENSE

2. In the app go to Messenger tab then click Setup Webhook. Here you will put in the URL of your Heroku server and a token. Make sure to check all the subscription fields. MAKES NO SENSE

NOT A TUTORIAL, WHICH MAKES YOU A RETARD!!!! :D

**Comment by keronk** [comment]
It made sense to everyone else who followed it. No need to be an arsehat,
You should also be aware Facebook has updated the process since this was
published so there are tweaks to it which will mean you have to use your
brain.

**Comment by matbeedotcom** [comment]
Okay, to be fair, this isn't a hold-your-hand tutorial. If this is beyond your current abilities, I might suggest you learn a bit more about webservices, and nodejs.

**Comment by jellyfangs** [comment]
@EddyTheLegoGuy courtesy will get you farther on the internet than not. You understand git, you understand commits, then remainder is understanding JavaScript, setting up servers, and integrating API services. There are plenty of resources available to gather those understandings to come back and try this again. I believe in you.
