### ISSUE TITLE
Bot only work with current user.

### ISSUE THREAD

**Issue by derozgurg** [jw84/messenger-bot-tutorial#41]
Hi, do you heve any idea why bot works with only current facebook account which created facebook page and api. Api doesn't work when another user send a message.

**Comment by LevinoMoises** [comment]
Until your app is not approved by Facebook, you have to be the admin of the app. You can add new admins by going to your App Admin Page > Roles.

**Comment by jellyfangs** [comment]
@derozgurg Hi, you can add additional users as testers in the Facebook Developer settings for the FB Page you're using. After your facebook chatbot is approved then everyone can talk to it without restrictions.
