### ISSUE TITLE
Working with Api

### ISSUE THREAD

**Issue by ksandeepvvn** [jw84/messenger-bot-tutorial#42]
Hi how to work with API's, please let me know

**Comment by torbenbru** [comment]
Hey i think you should check this out: https://developers.facebook.com/docs/graph-api?locale=de_DE
facebook describe their graph api there. You should also check out some tutorials on the api where people create simple scripts!

**Comment by ksandeepvvn** [comment]
Thats Done already i did it from Docs. Thank you,
Sandeep

**Comment by jellyfangs** [comment]
@ksandeepvvn I don't recommend using Social Graph API with Facebook chat bots. 

Reason being the Social Graph API requires an oAuth confirmation from the user. That means you need to display a webview with a separate web server that engages the user to approve an oAuth request, match the auth token with the FB user id, store that authorization token in your server. 

But for the amount of work you get very little back. The Social Graph API has been getting trimmed more and more. You no longer can post, update, or have access to very much information other than the personal profile.

It's better and easier to create a chat bot experience that asks for information from the user for now.

**Comment by ksandeepvvn** [comment]
You are right agree with you. Thanks for your help

**Comment by m-o-leary** [comment]
@jw84 - thanks a million for the tutorial- I found it excellent and a great intro to the world of Bots! I have a question on the WIT HTTP API - do you know of any step by step for conversing with the bot using ONLY the HTTP API (not any node/python wrapper)? Sorry as I already know this is the wrong place for this but I don't want to open a new issue for this question and I see you recently updated it so I might get your attention :)

**Comment by ksandeepvvn** [comment]
@buddythumbs Try Api.ai console, you can find more tutorials in documentation for developing bots.

**Comment by m-o-leary** [comment]
@ksandeepvvn thanks! I am able to work with the api in general and with good success but updating context is not really explained properly on the site. I don't want to hyjack this issue thread on a separate issue but I find it hard to get info from people who know!

**Comment by ksandeepvvn** [comment]
@buddythumbs updating contexts are like passing parameters from one class to another class, it has two types one is "Context In"(Input Parameter) and "Context Out"(Output Parameter), and they are passed by using parameter Values(Which you can find down to Action Field. If still you have doubts please try to work more hit and trail you will understand it.

**Comment by jellyfangs** [comment]
@buddythumbs I concur with @ksandeepvvn that api.ai is a better choice. I have another tutorial https://github.com/jw84/messenger-bot-witai-tutorial explaining how to use the wit.ai node wrapper but after a year I'm still not satisfied with them as a service.

**Comment by ghost** [comment]
@jw84 really? So you think there might be a better alternative out there? I literally knew nothing about bots before reading your articles so I would be interested in finding a better alternative if there is one! I'm only realising now that API.ai is referring to s completely different service. I will check that out!
