### ISSUE TITLE
Does not reply on users other than me

### ISSUE THREAD

**Issue by jannavarro** [jw84/messenger-bot-tutorial#45]
I followed the sample and got it working. Whenever I message the bot it echoes it. However when I asked other people to message the fb page there is no reply. Is your sample supposed to work with other users other than the one who created the fb page? If yes then I did something wrong which I'm thinking is because the fb page access token I put in Heroku config vars is only applicable for my user, is that correct?

**Comment by ghost** [comment]
I think they need to be added as admin to the app/page that the bot is messaging from as the app/page is not public. 

If you log the Heroku output it will show the authorization error (does with me anyway)

type <pre>heroku logs --tail</pre>in the terminal once you have pushed the project to server and you should get the live logging. Then message the bot from your account, see what it says (I have loads of console logs set up to see what's happening). Then message from another account - the error handler of the standard webhook post should show the error.

Having said all this - I couldn't get the system working with a dummy token so skipped that for the moment to just get up and running. 

If someone could explain the purpose of that step I would appreciate it!

**Comment by jannavarro** [comment]
@martin0852 THanks. The logs helped and you are correct that the user needs to be an admin if the page is not yet live. The actual error is: Error:  { message: '(#10) Cannot message users who are not admins, developers or testers of the app until pages_messaging permission is reviewed and the app is live.',
