### ISSUE TITLE
Why did you send a random page token?

### ISSUE THREAD

**Issue by lattice0** [jw84/messenger-bot-tutorial#48]
In this line:

` qs: {access_token:token},`

you're sending a random generated token. Shouldn't this be the page access token which you use to subscribe the page to webhooks?

**Comment by jellyfangs** [comment]
Hi, I'm sending a variable ````token``` that's assigned at runtime.

Variable token is assigned from the FB Page Access Token you'll find in the FB Developer settings for the FB page you're using.

![jw84_messenger-bot-tutorial__facebook_messenger_bot_15_minute_tutorial](https://cloud.githubusercontent.com/assets/48764/22009368/84d5a586-dc37-11e6-821a-ab8c01a04e99.jpg)

**Comment by bryansbc** [comment]
Hi Jerry can I understand why you are not replying dispite taking our project. The fact that you are making commit here means you are alive and well. We have fees paid to you please at less provide the code or refund our fee
