### ISSUE TITLE
No reply

### ISSUE THREAD

**Issue by x011** [jw84/messenger-bot-tutorial#7]
Hi there,
I'm not receiving any reply from the bot. is there any tip that you can share in order to make it work ?
I've set up the bot and everything is correct but I cannot receive the echo reply.
Thank you.

**Comment by joaocalixto** [comment]
Hi, I Had the same problem.

And I did this to work.

curl -X POST "https://graph.facebook.com/v2.6/me/subscribed_apps?access_token=<PAGE_ACCESS_TOKEN>"

**Comment by pas2al** [comment]
Everything works fine for me. Did you forget to pass the access token to the variable "var" in index.js? Have a look on line 50.

**Comment by farmanp** [comment]
Hi @pas2al, I'm not getting any responses either: my token was defined wrong but I fixed it and it's still no good. I went to my heorku app's webhook, and the interface says "Error, wrong token". But when I curled a post to the Facebook graph, it said: sucess: true

**Comment by pas2al** [comment]
Hm, there has to be some misconfiguration. Create a facebook app and a facebook page. Edit these configuration like in the README. Everything works fine for me, i tried it just a minute ago.

**Comment by zenper** [comment]
every step by step seem fine for me! but  i can't find where is my chatbot. I don't see my chatbot in Facebook page. Help me fix it. Thanks so much..

**Comment by zenper** [comment]
Hm. Every steps seem fine for me, but I can not receive any reply from chatbot. Please help me!

**Comment by zenper** [comment]
Thanks for all. I can do it. Chatbot is working. Feel so happy.
