### ISSUE TITLE
The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 503; HTTP Message = Service Unavailable

### ISSUE THREAD

**Issue by Tiththa** [jw84/messenger-bot-tutorial#75]
Im getting this error in the webhook setup.

> The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 503; HTTP Message = Service Unavailable

**Comment by vetrivelcsamy** [comment]
You need to point FB to the route that has the verify function within it. You are currently pointing FB to the site root index` '/' `it seems.

Change the FB webhook url in the app settings to` https://example.com/webhook `and the verification will be complete. FB will then send whatever events you subscribe to to your` '/webhook' `route

**Comment by Tiththa** [comment]
Thank you @vertrivelcsamy :)
