### ISSUE TITLE
Can bots initiate a conversation?

### ISSUE THREAD

**Issue by mandliya** [jw84/messenger-bot-tutorial#8]
I am making a simple reminder/to-do bot, just for fun. I wanted to know if bot can start a session(or conversation), say to remind me for a todo, at a cron event. I have been looking at various ways, couldn't yet figure out a way to do it.

**Comment by Melmer** [comment]
Yes you can.. but you need the sender id. I deleted a previous conversation with my bot (but saved my own sender id). After removing I posted a new request and received a new conversation from my bot.

You can perform a request like this:

```
curl -X POST -H "Content-Type: application/json" -d '{
    "recipient":{
        "id":USER_ID
    }, 
    "message":{
        "text":"hello, world!"
    }
}' "https://graph.facebook.com/v2.6/me/messages?access_token=PAGE_ACCESS_TOKEN"
```

Check also the complete guide: https://developers.facebook.com/docs/messenger-platform/implementation#send_message

**Comment by jellyfangs** [comment]
After the user talks to the chat bot once you can have the chat bot initiate the conversation there after. The best way is a cronjob, if using Heroku for hosting then you use their scheduler service.

**Comment by mandliya** [comment]
Cool Thanks guys! used node-cron and it worked!

**Comment by applenbt** [comment]
Do you know if you can initiate a group conversation between two or more people that have talked to the bot?

**Comment by ghost** [comment]
And do you guys know if there's a way to get that sender id by using the Facebook ID (usually obtained with the Facebook Login library)?

**Comment by ghost** [comment]
I have tried many ways to obtain that sender id from graph API, and I feel like trying out the next messenger plugin check (send to messenger) which unfortunately requires to pass several Facebook revisions and also adding your domain to the whitelist of your app

**Comment by sushant12** [comment]
@applenbt did u find a solution to that?
